# Generated by Django 6.0 on 2026-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audioUrl',
            field=models.FileField(max_length=500, upload_to='audios/'),
        ),
    ]
