# Generated by Django 6.0 on 2026-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_alter_audio_audiourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audioListId',
            field=models.CharField(max_length=20),
        ),
    ]
