# Generated by Django 6.0 on 2026-03-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_audio_audiolistid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['id'], 'verbose_name': 'audio-bg', 'verbose_name_plural': 'audio-bg'},
        ),
    ]
