# Generated by Django 6.0.5 on 2026-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload_path', models.CharField(help_text='Filesystem path to the uploaded video file (not a URL).', max_length=1000)),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('sloka_number', models.PositiveIntegerField()),
                ('book_name', models.CharField(choices=[('bhagavad_gita', 'Bhagavad Gita')], default='bhagavad_gita', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['book_name', 'chapter_number', 'sloka_number'],
                'unique_together': {('book_name', 'chapter_number', 'sloka_number')},
            },
        ),
    ]
