# Generated by Django 6.0.5 on 2026-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_upload_path',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', help_text='Upload the video file here.', max_length=1000, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
