# Generated by Django 6.0.5 on 2026-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_video_upload_path_video_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['book_name', 'chapter_number', 'sloka_number', 'language'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('english', 'English'), ('kannada', 'Kannada'), ('hindi', 'Hindi'), ('telugu', 'Telugu'), ('malayalam', 'Malayalam')], default='tamil', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('book_name', 'chapter_number', 'sloka_number', 'language')},
        ),
        migrations.RemoveField(
            model_name='video',
            name='chapter_name',
        ),
    ]
