# Generated by Django 6.0.5 on 2026-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_options_alter_video_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['book_name', 'chapter_number', 'sloka_start', 'language'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='video',
            name='sloka_start',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-populated: the first sloka in the range. Used for correct numeric ordering.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sloka_number',
            field=models.CharField(help_text="Sloka number or hyphen-separated range (e.g. '17-18', '1-2-3').", max_length=20),
        ),
    ]
