# Generated by Django 6.0 on 2026-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
