# Generated by Django 6.0 on 2026-02-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0002_imagegallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_image', models.ImageField(max_length=500, upload_to='image_gallery/categories/')),
                ('category_description', models.TextField(blank=True)),
                ('router_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Gallery Category',
                'verbose_name_plural': 'Image Gallery Categories',
                'ordering': ['category_name'],
            },
        ),
    ]
