# Generated by Django 6.0.5 on 2026-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0003_imagegallerycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='cdn_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
