# Generated by Django 6.0 on 2026-02-09 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vedic_scriptures', 'Vedic Scriptures'), ('prabhupada_books', 'Prabhupada Books'), ('puranas', 'Puranas'), ('articles', 'Articles'), ('research_documentations', 'Research Documentations'), ('tutorials', 'Tutorials'), ('stories', 'Stories'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('book_format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('doc', 'DOC'), ('docx', 'DOCX'), ('txt', 'TXT'), ('mobi', 'MOBI'), ('azw', 'AZW')], max_length=10)),
                ('book_url', models.FileField(max_length=500, upload_to='books/')),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book Library',
                'db_table': 'book_library',
                'ordering': ['-created_at'],
            },
        ),
    ]
