# Generated by Django 6.0.5 on 2026-05-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklibrary',
            options={'ordering': ['-created_at'], 'verbose_name': 'DocumentLibrary', 'verbose_name_plural': 'DocumentLibrary'},
        ),
        migrations.RemoveField(
            model_name='booklibrary',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='book_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('mobi', 'MOBI'), ('azw', 'AZW')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='category',
            field=models.CharField(choices=[('vedic_scriptures', 'Vedic Scriptures'), ('prabhupada_books', 'Prabhupada Books'), ('puranas', 'Puranas'), ('other_sampradaya_scriptures', 'Other Sampradaya scriptures'), ('articles', 'Articles'), ('research_documentations', 'Research Documentations'), ('tutorials', 'Tutorials'), ('stories', 'Stories'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='language',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('english', 'English'), ('hindi', 'Hindi'), ('sanskrit', 'Sanskrit'), ('kannada', 'Kannada'), ('telugu', 'Telugu'), ('bengali', 'Bengali'), ('malayalam', 'Malayalam'), ('marathi', 'Marathi')], max_length=100),
        ),
    ]
