version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: askharekrishna-postgres
    restart: always
    environment:
      POSTGRES_DB: askharekrishna
      POSTGRES_USER: askharekrishna_user
      POSTGRES_PASSWORD: AKhK_2026_dbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
