# Generated by Django 6.0 on 2026-04-08 02:53

import django.db.models.deletion
from django.db import migrations, models


def copy_main_topic_to_fk(apps, schema_editor):
    DebateArticle = apps.get_model('debate', 'DebateArticle')
    DebateMainTopic = apps.get_model('debate', 'DebateMainTopic')

    for article in DebateArticle.objects.order_by('id').only('id', 'mainTopic'):
        raw_topic = getattr(article, 'mainTopic', None)
        if not raw_topic:
            continue

        topic_name = str(raw_topic).strip()
        if not topic_name:
            continue

        topic, _ = DebateMainTopic.objects.get_or_create(name=topic_name)
        article.mainTopic_ref = topic
        article.save(update_fields=['mainTopic_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0094_seed_debate_tamil_batch_07'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='debate/category/')),
            ],
            options={
                'verbose_name': 'Debate Category',
                'verbose_name_plural': 'Debate Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DebateMainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='debate/main-topic/')),
            ],
            options={
                'verbose_name': 'Debate Main Topic',
                'verbose_name_plural': 'Debate Main Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='debatearticle',
            options={'ordering': ['order', 'mainTopic__name', 'subTopic'], 'verbose_name': 'Debate Article', 'verbose_name_plural': 'Debate Articles'},
        ),
        migrations.AddField(
            model_name='debatearticle',
            name='debateCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='debate.debatecategory'),
        ),
        migrations.AddField(
            model_name='debatearticle',
            name='mainTopic_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='debate.debatemaintopic'),
        ),
        migrations.RunPython(copy_main_topic_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='debatearticle',
            name='mainTopic',
        ),
        migrations.RenameField(
            model_name='debatearticle',
            old_name='mainTopic_ref',
            new_name='mainTopic',
        ),
    ]
