# Generated by Django 6.0 on 2026-04-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0095_debatecategory_debatemaintopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatemaintopic',
            name='debateCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_topics', to='debate.debatecategory'),
        ),
    ]
