# Generated by Django 6.0.5 on 2026-05-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0097_remove_maintopic_add_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debatearticle',
            options={'ordering': ['order', 'topic', 'subTopic'], 'verbose_name': 'Debate Article', 'verbose_name_plural': 'Debate Articles'},
        ),
        migrations.AlterField(
            model_name='debatearticle',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
