# Generated by Django 6.0.5 on 2026-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0099_debatearticle_rename_topic_and_add_translation_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatearticle',
            name='articleImage',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='debate/article/'),
        ),
    ]
