# Generated by Django 6.0 on 2026-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingarticle',
            name='audioPath',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='cooking/audio/'),
        ),
    ]
