# Generated by Django 6.0 on 2026-03-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTopic', models.CharField(max_length=255)),
                ('subTopic', models.CharField(max_length=255)),
                ('article', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Distribution',
                'verbose_name_plural': 'Book Distribution Articles',
                'ordering': ['order', 'mainTopic', 'subTopic'],
            },
        ),
    ]
