# Generated by Django 6.0 on 2026-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brahmhacaryaarticle',
            name='audioUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
