# Generated by Django 6.0 on 2026-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0002_brahmhacaryaarticle_audiourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brahmhacaryaarticle',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='brahmhacaryaarticle',
            name='category',
            field=models.CharField(choices=[('Roadmap', 'Roadmap'), ('CommonTrap', 'CommonTrap')], default='Roadmap', max_length=20),
        ),
    ]
