# Generated by Django 6.0 on 2026-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0003_remove_brahmhacaryaarticle_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brahmhacaryaarticle',
            name='audioUrl',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='brahmhacarya/audio/'),
        ),
    ]
