# Generated by Django 6.0 on 2026-02-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0004_alter_brahmhacaryaarticle_audiourl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brahmhacaryaarticle',
            options={'ordering': ['order', '-published_at', '-created_at'], 'verbose_name': 'Brahmhacarya Article', 'verbose_name_plural': 'Brahmhacarya Articles'},
        ),
        migrations.AddField(
            model_name='brahmhacaryaarticle',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brahmhacaryaarticle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brahmhacaryaarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
