# Generated by Django 6.0 on 2026-02-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0005_alter_brahmhacaryaarticle_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brahmhacaryaarticle',
            constraint=models.UniqueConstraint(condition=models.Q(('category', ''), _negated=True), fields=('category', 'order'), name='unique_order_per_brahmhacarya_category'),
        ),
    ]
