# Generated by Django 6.0 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0006_brahmhacaryaarticle_unique_order_per_brahmhacarya_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrahmhacaryaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('current_level', models.CharField(max_length=255)),
                ('spiritual_goal', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brahmhacarya Registration',
                'verbose_name_plural': 'Brahmhacarya Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
