# Generated by Django 6.0 on 2026-03-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0007_brahmhacaryaregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brahmhacaryaregistration',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='brahmhacaryaregistration',
            name='location',
        ),
        migrations.RemoveField(
            model_name='brahmhacaryaregistration',
            name='spiritual_goal',
        ),
        migrations.AddField(
            model_name='brahmhacaryaregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='brahmhacaryaregistration',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
