# Generated by Django 6.0 on 2026-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0008_remove_brahmhacaryaregistration_current_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brahmhacaryaarticle',
            options={'ordering': ['language', 'order', '-published_at', '-created_at'], 'verbose_name': 'Brahmhacarya Article', 'verbose_name_plural': 'Brahmhacarya Articles'},
        ),
        migrations.RemoveConstraint(
            model_name='brahmhacaryaarticle',
            name='unique_order_per_brahmhacarya_category',
        ),
        migrations.AddField(
            model_name='brahmhacaryaarticle',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='brahmhacaryaarticle',
            constraint=models.UniqueConstraint(condition=models.Q(('category', ''), _negated=True), fields=('language', 'category', 'order'), name='unique_order_per_brahmhacarya_language_category'),
        ),
    ]
