# Generated by Django 6.0.5 on 2026-05-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0009_alter_brahmhacaryaarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrahmhacaryaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='brahmhacarya.brahmhacaryaarticle')),
            ],
            options={
                'verbose_name': 'Brahmhacarya MCQ Question',
                'verbose_name_plural': 'Brahmhacarya MCQ Questions',
                'ordering': ['article_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrahmhacaryaQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='brahmhacarya.brahmhacaryaquestion')),
            ],
            options={
                'verbose_name': 'Brahmhacarya MCQ Option',
                'verbose_name_plural': 'Brahmhacarya MCQ Options',
                'ordering': ['question_id', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='brahmhacaryaquestion',
            constraint=models.UniqueConstraint(fields=('article', 'order'), name='uq_brahmhacarya_question_order'),
        ),
        migrations.AddConstraint(
            model_name='brahmhacaryaquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uq_brahmhacarya_option_order'),
        ),
    ]
