# Generated by Django 6.0 on 2026-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brahmhacarya', '0010_brahmhacaryaquestion_brahmhacaryaquestionoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrahmhacaryaUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('article_title', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brahmhacarya User Score',
                'verbose_name_plural': 'Brahmhacarya User Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
