# Generated by Django 6.0.5 on 2026-05-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weburlResource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weburlresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Web URL Resource', 'verbose_name_plural': 'Web URL Resources'},
        ),
    ]
