# Generated by Django 6.0 on 2026-04-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='storyCategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
