# Generated by Django 6.0 on 2026-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_storycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='storyCategory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['storyCategory', 'language', 'order'], name='story_cat_lang_ord_idx'),
        ),
    ]
