# Generated by Django 6.0.5 on 2026-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_story_imagepath'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['storyCategory', 'mainTopic', 'id'], name='story_cat_topic_id_idx'),
        ),
    ]
