# Generated by Django 6.0 on 2026-05-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_story_cat_topic_id_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='stories.story')),
            ],
            options={
                'verbose_name': 'Story MCQ Question',
                'verbose_name_plural': 'Story MCQ Questions',
                'ordering': ['story_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stories.storyquestion')),
            ],
            options={
                'verbose_name': 'Story MCQ Option',
                'verbose_name_plural': 'Story MCQ Options',
                'ordering': ['question_id', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='storyquestion',
            constraint=models.UniqueConstraint(fields=('story', 'order'), name='uq_story_question_order'),
        ),
        migrations.AddConstraint(
            model_name='storyquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uq_story_option_order'),
        ),
    ]
