# Generated by Django 6.0.5 on 2026-05-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_storyquestion_storyquestionoption'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='story_cat_lang_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='story_cat_topic_id_idx',
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['mainTopic', 'language', 'order'], name='story_topic_lang_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['mainTopic', 'id'], name='story_topic_id_idx'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='storyCategory',
        ),
        migrations.DeleteModel(
            name='StoryCategory',
        ),
    ]
