# Generated by Django 6.0.5 on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_remove_story_story_cat_lang_ord_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source_story',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='translations',
                to='stories.story',
            ),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(
                condition=Q(source_story__isnull=False),
                fields=('source_story', 'language'),
                name='uq_story_source_language',
            ),
        ),
    ]
