# Generated by Django 6.0 on 2026-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaishnava_etiquettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaishnavaetiquette',
            name='audioPath',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='vaishnava_etiquettes/audio/'),
        ),
    ]
