# Generated by Django 6.0 on 2026-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kirtan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ragaTalaName', models.CharField(max_length=200)),
                ('beatSwara', models.CharField(max_length=200)),
                ('audioPath', models.FileField(blank=True, max_length=500, null=True, upload_to='kirtans/audio/')),
                ('videoPath', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kirtan',
                'verbose_name_plural': 'Kirtans',
                'ordering': ['-created_at'],
            },
        ),
    ]
