# Generated by Django 6.0.5 on 2026-05-08 23:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirtan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KirtanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('categoryImage', models.ImageField(blank=True, max_length=500, null=True, upload_to='kirtans/categories/')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kirtan Category',
                'verbose_name_plural': 'Kirtan Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='kirtan',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Kirtan', 'verbose_name_plural': 'Kirtans'},
        ),
        migrations.RemoveField(
            model_name='kirtan',
            name='beatSwara',
        ),
        migrations.RemoveField(
            model_name='kirtan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kirtan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='kirtan',
            name='ragaTalaName',
        ),
        migrations.RemoveField(
            model_name='kirtan',
            name='title',
        ),
        migrations.AddField(
            model_name='kirtan',
            name='imagePath',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='kirtans/images/'),
        ),
        migrations.AddField(
            model_name='kirtan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for frontend sorting'),
        ),
        migrations.AlterField(
            model_name='kirtan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kirtans', to='kirtan.kirtancategory'),
        ),
        migrations.CreateModel(
            name='KirtanCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kirtan.kirtancategory')),
            ],
            options={
                'verbose_name': 'Kirtan Category Translation',
                'verbose_name_plural': 'Kirtan Category Translations',
                'unique_together': {('category', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='KirtanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('authorName', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('lyrics', models.TextField(blank=True)),
                ('kirtan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kirtan.kirtan')),
            ],
            options={
                'verbose_name': 'Kirtan Translation',
                'verbose_name_plural': 'Kirtan Translations',
                'unique_together': {('kirtan', 'language_code')},
            },
        ),
    ]
