# Generated by Django 6.0.5 on 2026-07-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirtan', '0002_kirtancategory_alter_kirtan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirtancategory',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='kirtancategorytranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='kirtantranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', max_length=10),
        ),
    ]
