# Generated by Django 6.0 on 2026-03-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantingarticle',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
