# Generated by Django 6.0 on 2026-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanting', '0002_chantingarticle_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantingarticle',
            name='audioPath',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='chanting/audio/'),
        ),
    ]
