# Generated by Django 6.0 on 2026-07-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanting', '0003_chantingarticle_audiopath'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantingarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chanting.chantingarticle'),
        ),
    ]
