# Generated by Django 6.0 on 2026-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanting', '0004_chantingarticle_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTopicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_topic', models.CharField(help_text='The exact English Main Topic string', max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('translated_topic', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('english_topic', 'language')},
            },
        ),
    ]
