# Generated by Django 6.0 on 2026-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnaticquestion',
            name='audio',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='carnatic_questions/audio/'),
        ),
    ]
