# Generated by Django 6.0 on 2026-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0004_alter_carnaticsyllabus_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnaticsyllabus',
            name='lesson',
            field=models.CharField(max_length=9000),
        ),
    ]
