# Generated by Django 6.0 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0005_alter_carnaticsyllabus_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnaticsyllabus',
            name='lesson',
            field=models.TextField(),
        ),
    ]
