# Generated by Django 6.0 on 2026-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0006_alter_carnaticsyllabus_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnaticsyllabus',
            name='videoPath',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='carnatic_syllabus/video/'),
        ),
    ]
