# Generated by Django 6.0 on 2026-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0007_carnaticsyllabus_videopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnaticsyllabus',
            name='videoPath',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
