# Generated by Django 6.0 on 2026-04-24 10:12

import django.db.models.deletion
from django.db import migrations, models


def copy_divisions_to_categories(apps, schema_editor):
    Category = apps.get_model('carnatic_questions', 'Category')
    CarnaticSyllabus = apps.get_model('carnatic_questions', 'CarnaticSyllabus')

    for syllabus in CarnaticSyllabus.objects.exclude(division__isnull=True).exclude(division__exact=''):
        category, _ = Category.objects.get_or_create(name=syllabus.division.strip())
        syllabus.category = category
        syllabus.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0008_alter_carnaticsyllabus_videopath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='carnaticsyllabus',
            options={'ordering': ['category__name', 'topic', 'lesson'], 'verbose_name': 'Carnatic Syllabus', 'verbose_name_plural': 'Carnatic Syllabus'},
        ),
        migrations.AddField(
            model_name='carnaticquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='carnatic_questions.category'),
        ),
        migrations.AddField(
            model_name='carnaticsyllabus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_items', to='carnatic_questions.category'),
        ),
        migrations.RunPython(copy_divisions_to_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='carnaticsyllabus',
            name='division',
        ),
    ]
