# Generated by Django 6.0 on 2026-04-24 10:17

import django.db.models.deletion
from django.db import migrations, models


def copy_video_paths_to_samples(apps, schema_editor):
    CarnaticSyllabus = apps.get_model('carnatic_questions', 'CarnaticSyllabus')
    CarnaticSyllabusVideoSample = apps.get_model('carnatic_questions', 'CarnaticSyllabusVideoSample')

    for syllabus in CarnaticSyllabus.objects.exclude(videoPath__isnull=True).exclude(videoPath__exact=''):
        CarnaticSyllabusVideoSample.objects.create(syllabus=syllabus, url=syllabus.videoPath.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0009_category_alter_carnaticsyllabus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnaticSyllabusVideoSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_samples', to='carnatic_questions.carnaticsyllabus')),
            ],
            options={
                'verbose_name': 'Carnatic Syllabus Video Sample',
                'verbose_name_plural': 'Carnatic Syllabus Video Samples',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_video_paths_to_samples, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='carnaticsyllabus',
            name='videoPath',
        ),
    ]
