# Generated by Django 6.0 on 2026-04-24 10:20

from django.db import migrations, models


def populate_video_sample_sort_order(apps, schema_editor):
    CarnaticSyllabusVideoSample = apps.get_model('carnatic_questions', 'CarnaticSyllabusVideoSample')

    syllabus_ids = CarnaticSyllabusVideoSample.objects.order_by().values_list('syllabus_id', flat=True).distinct()
    for syllabus_id in syllabus_ids:
        samples = CarnaticSyllabusVideoSample.objects.filter(syllabus_id=syllabus_id).order_by('id')
        for index, sample in enumerate(samples):
            sample.sort_order = index
            sample.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0010_remove_carnaticsyllabus_videopath_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carnaticsyllabusvideosample',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Carnatic Syllabus Video Sample', 'verbose_name_plural': 'Carnatic Syllabus Video Samples'},
        ),
        migrations.AddField(
            model_name='carnaticsyllabusvideosample',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(populate_video_sample_sort_order, migrations.RunPython.noop),
    ]
