# Generated by Django 6.0 on 2026-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0011_alter_carnaticsyllabusvideosample_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnaticKacheri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=255)),
                ('ragam', models.CharField(max_length=255)),
                ('videoUrl', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carnatic Kacheri',
                'verbose_name_plural': 'Carnatic Kacheri',
                'ordering': ['singer', 'ragam', '-created_at'],
            },
        ),
    ]
