# Generated by Django 6.0.5 on 2026-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0014_alter_category_options_category_colorcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnaticClassAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audioPath', models.FileField(max_length=500, upload_to='carnatic_class_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carnatic Class Audio',
                'verbose_name_plural': 'Carnatic Class Audios',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
