# Generated by Django 6.0.5 on 2026-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0015_carnaticclassaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnaticLessonPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PracticeCategory', models.CharField(max_length=255)),
                ('lessonName', models.CharField(max_length=255)),
                ('audioPath', models.FileField(max_length=500, upload_to='carnatic_lesson_practice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carnatic Lesson Practice',
                'verbose_name_plural': 'Carnatic Lesson Practices',
                'ordering': ['-created_at', 'PracticeCategory', 'lessonName'],
            },
        ),
    ]
