# Generated by Django 6.0.5 on 2026-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic_questions', '0016_carnaticlessonpractice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnaticlessonpractice',
            name='PracticeCategory',
            field=models.CharField(choices=[('Sarali Varisaigal', 'Sarali Varisaigal'), ('Jantai Varisaigal', 'Jantai Varisaigal'), ('Dhattu Varisaigal', 'Dhattu Varisaigal'), ('Mel Sthayi Varisaigal', 'Mel Sthayi Varisaigal'), ('Keezh Sthayi Varisaigal', 'Keezh Sthayi Varisaigal'), ('Alankaarams', 'Alankaarams'), ('Gitam Lessons', 'Gitam Lessons')], default='Sarali Varisaigal', max_length=50),
        ),
    ]
