# Generated by Django 6.0 on 2026-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurOtherSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.URLField(max_length=500)),
                ('purpose', models.TextField()),
                ('features_available', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Other Site',
                'verbose_name_plural': 'Our Other Sites',
                'ordering': ['-created_at'],
            },
        ),
    ]
