# Generated by Django 6.0.5 on 2026-05-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.PositiveIntegerField()),
                ('article_title', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('pooja_vidhi', 'Pooja Vidhi'), ('story', 'Story')], default='pooja_vidhi', max_length=32)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='subscribers.subscriber')),
            ],
            options={
                'verbose_name': 'Subscriber Quiz Attempt',
                'verbose_name_plural': 'Subscriber Quiz Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber', 'quiz_type', 'article_id'], name='quiz_attempt_lookup_idx'), models.Index(fields=['created_at'], name='quiz_attempt_created_idx')],
            },
        ),
    ]
