# Generated by Django 6.0 on 2026-07-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True, help_text='Date of the calendar day (YYYY-MM-DD)', unique=True)),
                ('day_of_week', models.CharField(help_text='Day of the week (e.g., Thursday)', max_length=20)),
                ('is_ekadashi', models.BooleanField(default=False, help_text='Whether this day is an Ekadashi')),
                ('ekadashi_name', models.CharField(blank=True, help_text='Name of Ekadashi if applicable', max_length=150, null=True)),
                ('is_fast_day', models.BooleanField(default=False, help_text='Whether fasting is required on this day')),
                ('fast_details', models.TextField(blank=True, help_text='Specific fasting details or instructions', null=True)),
                ('break_fast_start', models.DateTimeField(blank=True, help_text='Break fast (Parana) start datetime', null=True)),
                ('break_fast_end', models.DateTimeField(blank=True, help_text='Break fast (Parana) end datetime', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Day',
                'verbose_name_plural': 'Calendar Days',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarObservance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of observance or festival', max_length=255)),
                ('category', models.CharField(choices=[('Ekadashi', 'Ekadashi'), ('Parana', 'Parana'), ('Appearance', 'Appearance / Disappearance'), ('Festival', 'Festival'), ('Fasting', 'Fasting Note'), ('Observance', 'General Observance')], default='Observance', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional notes or details', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observances', to='vaishnava_calendar.calendarday')),
            ],
            options={
                'verbose_name': 'Calendar Observance',
                'verbose_name_plural': 'Calendar Observances',
                'ordering': ['order', 'id'],
            },
        ),
    ]
