# Generated by Django 6.0 on 2026-07-28 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaishnava_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarobservance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendarobservance',
            name='title',
        ),
        migrations.AddField(
            model_name='calendarobservance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendarobservance',
            name='image',
            field=models.ImageField(blank=True, help_text='Common image for all languages', max_length=500, null=True, upload_to='vaishnava_calendar/images/'),
        ),
        migrations.AddField(
            model_name='calendarobservance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CalendarObservanceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('bn', 'Bengali')], default='en', help_text='Language of this translation', max_length=10)),
                ('title', models.CharField(help_text='Title in specific language', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or details', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Language-specific audio file', max_length=500, null=True, upload_to='vaishnava_calendar/audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vaishnava_calendar.calendarobservance')),
            ],
            options={
                'verbose_name': 'Observance Translation',
                'verbose_name_plural': 'Observance Translations',
                'ordering': ['language_code', 'id'],
                'unique_together': {('observance', 'language_code')},
            },
        ),
    ]
