# Generated by Django 6.0 on 2026-03-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojavidhi',
            name='audioPath',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='pooja_vidhis/audio/'),
        ),
    ]
