# Generated by Django 6.0.5 on 2026-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0002_poojavidhi_audiopath'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojavidhi',
            name='articleImage',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='pooja_vidhis/images/'),
        ),
    ]
