# Generated by Django 6.0.5 on 2026-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0003_poojavidhi_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaVidhiTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pooja Vidhi Topic',
                'verbose_name_plural': 'Pooja Vidhi Topics',
                'ordering': ['order', 'name'],
            },
        ),
    ]
