# Generated by Django 6.0.5 on 2026-05-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0004_poojavidhitopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojavidhi',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ta', 'ta')], default='en', max_length=10),
        ),
    ]
