# Generated by Django 6.0.5 on 2026-05-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0005_alter_poojavidhi_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojavidhi',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True),
        ),
    ]
