# Generated by Django 6.0 on 2026-05-22 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_vidhis', '0006_alter_poojavidhi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaVidhiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pooja_vidhi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pooja_vidhis.poojavidhi')),
            ],
            options={
                'verbose_name': 'Pooja Vidhi MCQ Question',
                'verbose_name_plural': 'Pooja Vidhi MCQ Questions',
                'ordering': ['pooja_vidhi_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PoojaVidhiQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pooja_vidhis.poojavidhiquestion')),
            ],
            options={
                'verbose_name': 'Pooja Vidhi MCQ Option',
                'verbose_name_plural': 'Pooja Vidhi MCQ Options',
                'ordering': ['question_id', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='poojavidhiquestion',
            constraint=models.UniqueConstraint(fields=('pooja_vidhi', 'order'), name='uq_pooja_vidhi_question_order'),
        ),
        migrations.AddConstraint(
            model_name='poojavidhiquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uq_pooja_vidhi_option_order'),
        ),
    ]
